# Stage 1
FROM node:18.16.0-bullseye-slim as build-stage

WORKDIR /Client
COPY package*.json ./
RUN npm install
COPY . .
ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

CMD ["npm", "start"]
