version: '3.9'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ../test_database/test_data/mysql_db:/var/lib/mysql
      - ../test_database/DDL_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
volumes:
  mysql_db:

  