version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: madeinchina
      MYSQL_PASSWORD: madeinchina
      MYSQL_DATABASE: db_test
    ports:
      - 3306:3306
    volumes:
      - .test/db_test/mysql_db:/var/lib/mysql